apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: mern-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: mohanbabu66/backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongo-uri
